name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Ajout explicite de pytest
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
    
    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker build -t accroCodeur1/flask-content-platform:latest .
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u accroCodeur1 --password-stdin
        docker push accroCodeur1/flask-content-platform:latest